#-----------------------------------------------------------------#
#  Developer: Aldo Vera-Espinoza & Jeremy Palomo  ___     _______   ___       _ ____  #
#  Date: Sun Aug 25 14:49:36 2024                / \ \   / / ____| ( _ )     | |  _ \ #
#                                               / _ \ \ / /|  _|   / _ \/\_  | | |_) |#
#  Project Name: CooolJournal Makefile         / ___ \ V / | |___ | (_>  < |_| |  __/ #
#  Description:                               /_/   \_\_/  |_____| \___/\/\___/|_|    #
#    Makefile that sets up the envrioment and has                 #
#  other utility.                                                 #
#-----------------------------------------------------------------#

 ifeq (, $(shell which npm))
 $(error "No npm in $(PATH); please install npm")
 endif

run:
	npm run dev